name: Pipeline Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install dependencies
        run: npm install

      - name: Read skip-tests configuration
        id: read_config
        run: |
          skip_tests=$(jq '.skipTests' skip-tests.config.json)
          echo "RUN_TESTS=${skip_tests}" >> $GITHUB_ENV

      - name: Run linter
        run: npm run lint

      - name: Debug RUN_TESTS
        run: echo "RUN_TESTS is set to $RUN_TESTS"
        env:
          RUN_TESTS: ${{ env.RUN_TESTS }}

      - name: Run unit tests
        if: env.RUN_TESTS == 'true'
        run: npm test